services:
  influxdb:
    container_name: parkme/influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    ports:
      - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.5
    profiles:
     - production
     - emulation

  grafana:
    image: parkme/grafana
    build:
      context: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.6
    profiles:
     - production
     - emulation

  emulator:
    image: parkme/emulator
    build:
      context: emulator
    networks:
      metrics:
        ipv4_address: 172.19.1.7
    profiles:
      - emulation
    configs:
      - emulator.yml

configs:
  emulator.yml: 
    file: ${DOCKER_EMULATOR_CONFIG:-emulator/emulator.yml}

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  metrics:
    name: docker_metrics
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
